apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-web-lightclient
  labels:
    app: kubernetes-web-lightclient
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: kubernetes-web-lightclient
  template:
    metadata:
      labels:
        app: kubernetes-web-lightclient
    spec:
      containers:
        - image: kubernetes-web-lightclient
          name: kubernetes-web-lightclient
          resources:
            limits:
              memory: 500Mi
              cpu: 1
            requests:
              memory: 20Mi
              cpu: 100m
          volumeMounts:
            - mountPath: /data
              name: pod-volume
          imagePullPolicy: Always
      volumes:
        - name: pod-volume
          persistentVolumeClaim:
            claimName: kubernetes-web-lightclient
