apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-light-config
data:
  config.json: |
    {
      "STATS_FETCH_FREQUENCY": "60",
      "STATS_RETENTION": "86400",
      "OPENTELEMETRY_COLLECTOR_HTTP_TRACES": "12",
      "OPENTELEMETRY_COLLECTOR_HTTP_METRICS": "7",
      "OPENTELEMETRY_COLLECTOR_HTTP_LOGS": "",
      "OPENTELEMETRY_COLLECTOR_EXPORT_LOGS_INTERVAL_SECONDS": "60",
      "OPENTELEMETRY_COLLECTOR_EXPORT_METRICS_INTERVAL_SECONDS": "60",
      "OPENTELEMETRY_COLLECT_AUTHORIZATION_HEADER": ""
    }
